server:
  port: 8090

spring:
  application:
    name: file
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://postgres:5432/postgres
    user: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:admin123}
  bucket: ${MINIO_BUCKET:oxygen-bucket}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    enabled: false
