server:
  port: 8090

spring:
  application:
    name: file
  r2dbc:
    url: ${FILE_DB_URL:r2dbc:postgresql://postgres:5432/postgres}
    username: ${FILE_DB_USERNAME:postgres}
    password: ${FILE_DB_PASSWORD:postgres}
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true
minio:
  url: http://localhost:9000
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:admin123}
  bucket: ${MINIO_BUCKET:oxygen-bucket}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL:http://eureka:8761/eureka}

token:
  secret:
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQSflKxwRJSMeKKF2QT4fwpMeJf36POk6yJVadQssw5c
