server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/users/**,/auth/**,/admin/**
        - id: department
          uri: lb://department
          predicates:
            - Path=/departments/**, /rooms/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: oxygen
          uri: lb://oxygen
          predicates:
            - Path=/storages/**, /oxygen-supply/**
        - id: file
          uri: lb://file
          predicates:
            - Path=/upload/**, /download/**
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/ws/**
          filters:
            - RewritePath=/api/v1/notifications/ws/(?<segment>/?.*), /ws/$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/