server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/users/**,/auth/**,/admin/**
        - id: department
          uri: lb://department
          predicates:
            - Path=/departments/**, /rooms/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: oxygen
          uri: lb://oxygen
          predicates:
            - Path=/storages/**, /oxygen-supply/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh