server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: http://auth:8085
          predicates:
            - Path=/users/**,/auth/**,/admin/**,swagger-ui/**
        - id: department
          uri: http://department:8086
          predicates:
            - Path=/departments/**,/rooms/**
        - id: order
          uri: http://order:8087
          predicates:
            - Path=/orders/**
        - id: oxygen
          uri: http://oxygen:8096
          predicates:
            - Path=/storages/**, /oxygen-supply/**
        - id: file
          uri: lb://file
          predicates:
            - Path=/files/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh