server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: http://auth:8085
          predicates:
            - Path=/users/**,/register/**,/authenticate/**,/admin/**,/v3/api-docs/**
        - id: department
          uri: http://department:8086
          predicates:
            - Path=/departments/**,/rooms/**,/v3/api-docs/**
        - id: order
          uri: http://order:8087
          predicates:
            - Path=/orders/**
        - id: oxygen
          uri: http://oxygen:8096
          predicates:
            - Path=/storages/**,/oxygen-supply/**
        - id: file
          uri: lb://file:8090
          predicates:
            - Path=/files/**

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /auth/v3/api-docs
        name: Auth Service
      - url: /department/v3/api-docs
        name: Department Service
      - url: /file/v3/api-docs
        name: File Service
      - url: /order/v3/api-docs
        name: Order Service
      - url: /oxygen/v3/api-docs
        name: Oxygen Service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh