server:
  port: 8091

spring:
  application:
    name: notification
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: kafka1:29092,kafka2:29093,kafka3:29094
    topics:
      department-update-in:
        name: "department_update_in"
        group-id: "department_group"
      order-update-in:
        name: "order_update_in"
        group-id: "order_group"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/