server:
  port: 8096

spring:
  application:
    name: oxygen
  datasource:
    url: ${OXYGEN_DB_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${OXYGEN_DB_USERNAME:postgres}
    password: ${OXYGEN_DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
  main:
    allow-circular-references: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    circuitbreaker:
      hystrix:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL:http://eureka:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: refresh